language: clojure
jdk: oraclejdk8
lein: 2.6.1

before_script:
  - echo $SKYGEAR_SSH_KEY | sed "s/\\\\/\n/g" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo "Host git.skygeario.com" >> ~/.ssh/config
  - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
script:
  - test/test.sh
